version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: lira_rh_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lira_secure_password_2026
      POSTGRES_DB: lira_rh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lira_rh_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:lira_secure_password_2026@db:5432/lira_rh
      - UPLOAD_DIR=/app/uploads
      - JWT_SECRET=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    ports:
      - "8000:8000"
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lira_rh_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  uploads_data:
